export default Object.freeze({
    INITIALIZE:             'INITIALIZE',
    START_FETCHING_AUTH:    'START_FETCHING_AUTH',
    STOP_FETCHING_AUTH:     'STOP_FETCHING_AUTH',
    START_FETCHING_FEED:    'START_FETCHING_FEED',
    STOP_FETCHING_FEED:     'STOP_FETCHING_FEED'
});
