export default Object.freeze({
    LOGIN:          'LOGIN',
    LOGIN_SUCCESS:  'LOGIN_SUCCESS',
    LOGIN_FAIL:     'LOGIN_FAIL',

    SIGNUP:         'SIGNUP',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAIL:    'SIGNUP_FAIL',

    LOGOUT:         'LOGOUT',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL:    'LOGOUT_FAIL',

    LOGIN_GUEST: 'LOGIN_GUEST',
    LOGIN_GUEST_SUCCESS:  'LOGIN_GUEST_SUCCESS',
    LOGIN_GUEST_FAIL:     'LOGIN_GUEST_FAIL'
});