export default Object.freeze({
    FETCH_DETAILED_MOVIE:         'FETCH_DETAILED_MOVIE',
    FETCH_DETAILED_MOVIE_SUCCESS: 'FETCH_DETAILED_MOVIE_SUCCESS',
    FETCH_DETAILED_MOVIE_FAIL:    'FETCH_DETAILED_MOVIE_FAIL',
    CLEAR_DETAILED_MOVIE:         'CLEAR_DETAILED_MOVIE'
});
