export default Object.freeze({
    FETCH_WATCHLIST:         'FETCH_WATCHLIST',
    FETCH_WATCHLIST_SUCCESS: 'FETCH_WATCHLIST_SUCCESS',
    FETCH_WATCHLIST_FAIL:    'FETCH_WATCHLIST_FAIL',

    ADD_TO_WATCHLIST:         'ADD_TO_WATCHLIST',
    ADD_TO_WATCHLIST_SUCCESS: 'ADD_TO_WATCHLIST_SUCCESS',
    ADD_TO_WATCHLIST_FAIL:    'ADD_TO_WATCHLIST_FAIL',

    DELETE_FROM_WATCHLIST:         'DELETE_FROM_WATCHLIST',
    DELETE_FROM_WATCHLIST_SUCCESS: 'DELETE_FROM_WATCHLIST_SUCCESS',
    DELETE_FROM_WATCHLIST_FAIL:    'DELETE_FROM_WATCHLIST_FAIL',

    CHECK_MOVIE_IN_WATCHLIST:         'CHECK_MOVIE_IN_WATCHLIST',
    CHECK_MOVIE_IN_WATCHLIST_SUCCESS: 'CHECK_MOVIE_IN_WATCHLIST_SUCCESS',
    CHECK_MOVIE_IN_WATCHLIST_FAIL:    'CHECK_MOVIE_IN_WATCHLIST_FAIL'
});
