export default Object.freeze({
    FETCH_WATCHLIST:         'FETCH_WATCHLIST',
    FETCH_WATCHLIST_SUCCESS: 'FETCH_WATCHLIST_SUCCESS',
    FETCH_WATCHLIST_FAIL:    'FETCH_WATCHLIST_FAIL',

    ADD_TO_WATCHLIST:         'ADD_TO_WATCHLIST',
    ADD_TO_WATCHLIST_SUCCESS: 'ADD_TO_WATCHLIST_SUCCESS',
    ADD_TO_WATCHLIST_FAIL:    'ADD_TO_WATCHLIST_FAIL'
});
