// Types
export default Object.freeze({
    FETCH_NEW_MOVIES:         'FETCH_NEW_MOVIES',
    FETCH_NEW_MOVIES_SUCCESS: 'FETCH_NEW_MOVIES_SUCCESS',
    FETCH_NEW_MOVIES_FAIL:    'FETCH_NEW_MOVIES_FAIL',

    FETCH_POPULAR_MOVIES:         'FETCH_POPULAR_MOVIES',
    FETCH_POPULAR_MOVIES_SUCCESS: 'FETCH_POPULAR_MOVIES_SUCCESS',
    FETCH_POPULAR_MOVIES_FAIL:    'FETCH_POPULAR_MOVIES_FAIL',

    FETCH_EXPECTED_MOVIES:      'FETCH_EXPECTED_MOVIES',
    FETCH_EXPECTED_SUCCESS:     'FETCH_EXPECTED_MOVIES_SUCCESS',
    FETCH_EXPECTED_MOVIES_FAIL: 'FETCH_EXPECTED_MOVIES_FAIL',

    LIKE_MOVIE:         'LIKE_MOVIE',
    LIKE_MOVIE_SUCCESS: 'LIKE_MOVIE_SUCCESS',
    LIKE_MOVIE_FAIL:    'LIKE_MOVIE_FAIL'
});
