// Types
export default Object.freeze({
    FETCH_NEW_MOVIES:         'FETCH_NEW_MOVIES',
    FETCH_NEW_MOVIES_SUCCESS: 'FETCH_NEW_MOVIES_SUCCESS',
    FETCH_NEW_MOVIES_FAIL:    'FETCH_NEW_MOVIES_FAIL',

    FETCH_POPULAR_MOVIES:         'FETCH_POPULAR_MOVIES',
    FETCH_POPULAR_MOVIES_SUCCESS: 'FETCH_POPULAR_MOVIES_SUCCESS',
    FETCH_POPULAR_MOVIES_FAIL:    'FETCH_POPULAR_MOVIES_FAIL',

    FETCH_UPCOMING_MOVIES:         'FETCH_UPCOMING_MOVIES',
    FETCH_UPCOMING_MOVIES_SUCCESS: 'FETCH_UPCOMING_MOVIES_SUCCESS',
    FETCH_UPCOMING_MOVIES_FAIL:    'FETCH_UPCOMING_MOVIES_FAIL',

    FETCH_TOPRATED_MOVIES:         'FETCH_TOPRATED_MOVIES',
    FETCH_TOPRATED_MOVIES_SUCCESS: 'FETCH_TOPRATED_MOVIES_SUCCESS',
    FETCH_TOPRATED_MOVIES_FAIL:    'FETCH_TOPRATED_MOVIES_FAIL',

    FETCH_GENRES:         'FETCH_GENRES',
    FETCH_GENRES_SUCCESS: 'FETCH_GENRES_SUCCESS',
    FETCH_GENRES_FAIL:    'FETCH_GENRES_FAIL',

    FETCH_WISHLIST:         'FETCH_WISHLIST_LIST',
    FETCH_WISHLIST_SUCCESS: 'FETCH_WISHLIST_SUCCESS',
    FETCH_WISHLIST_FAIL:    'FETCH_WISHLIST_FAIL'
});
