// Types
export default Object.freeze({
    FETCH_MOVIES:         'FETCH_MOVIES',
    FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
    FETCH_MOVIES_FAIL:    'FETCH_MOVIES_FAIL',

    FETCH_GENRES:         'FETCH_GENRES',
    FETCH_GENRES_SUCCESS: 'FETCH_GENRES_SUCCESS',
    FETCH_GENRES_FAIL:    'FETCH_GENRES_FAIL'
});
