// Types
export default Object.freeze({
    FILL_USER_PROFILE:      'FILL_USER_PROFILE',
    CLEAR_USER_PROFILE:     'CLEAR_USER_PROFILE',

    UPDATE_PROFILE:         'UPDATE_PROFILE',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAIL:    'UPDATE_PROFILE_FAIL'
});
